const KIMYALAB_DATA = {
    users: [
        { username: 'ali', password: '123', title: 'Çaylak', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ali' },
        { username: 'ayse', password: '456', title: 'Atom Avcısı', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ayse' },
        { username: 'mehmet', password: '789', title: 'Karışım Ustası', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mehmet' },
        { username: 'fatma', password: '101', title: 'Elektron Efendisi', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatma' },
        { username: 'can', password: '202', title: 'Süper Simyacı', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Can' },
        { username: 'elif', password: '303', title: 'Çaylak', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elif' },
        { username: 'ozan', password: '404', title: 'Çaylak', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ozan' },
        { username: 'sude', password: '505', title: 'Çaylak', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sude' },
        { username: 'berk', password: '606', title: 'Çaylak', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Berk' },
        { username: 'ipek', password: '707', title: 'Çaylak', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ipek' }
    ],

    // FULL PERİODİC TABLE (1-118)
    elements: [
        { n: 1, s: "H", name: "Hidrojen", cat: "nonmetal", desc: "Evrenin %75'ini oluşturan en hafif elementtir." },
        { n: 2, s: "He", name: "Helyum", cat: "noble", desc: "Güneş'te gerçekleşen nükleer füzyonun temelidir." },
        { n: 3, s: "Li", name: "Lityum", cat: "alkali", desc: "En hafif metaldir, pillerde yaygın olarak kullanılır." },
        { n: 4, s: "Be", name: "Berilyum", cat: "alkaline", desc: "Havacılık ve uzay sanayisinde kullanılan sert bir metaldir." },
        { n: 5, s: "B", name: "Bor", cat: "metalloid", desc: "Türkiye dünyadaki en büyük bor rezervlerine sahiptir." },
        { n: 6, s: "C", name: "Karbon", cat: "nonmetal", desc: "Yaşamın temelidir; elmas ve grafit karbonun formlarıdır." },
        { n: 7, s: "N", name: "Azot", cat: "nonmetal", desc: "Atmosferin %78'ini oluşturur, soğutma işlemlerinde kullanılır." },
        { n: 8, s: "O", name: "Oksijen", cat: "nonmetal", desc: "Solunum ve yanma olayları için hayati önem taşır." },
        { n: 9, s: "F", name: "Flor", cat: "halogen", desc: "En elektronegatif elementtir, diş macunlarında bulunur." },
        { n: 10, s: "Ne", name: "Neon", cat: "noble", desc: "Tabelalarda parlak turuncu-kırmızı ışık vermek için kullanılır." },
        { n: 11, s: "Na", name: "Sodyum", cat: "alkali", desc: "Sofra tuzunun bir bileşenidir, suyla şiddetli tepkime verir." },
        { n: 12, s: "Mg", name: "Magnezyum", cat: "alkaline", desc: "Hafiftir ve klorofilin merkez atomunu oluşturur." },
        { n: 13, s: "Al", name: "Alüminyum", cat: "transition", desc: "İçecek kutuları ve mutfak folyoları için ideal bir metaldir." },
        { n: 14, s: "Si", name: "Silisyum", cat: "metalloid", desc: "Bilgisayar çipleri ve güneş pillerinde ana malzemedir." },
        { n: 15, s: "P", name: "Fosfor", cat: "nonmetal", desc: "Canlıların DNA ve ATP yapısında yer alan kritik bir maddedir." },
        { n: 16, s: "S", name: "Kükürt", cat: "nonmetal", desc: "Barut ve sülfürik asit üretiminde kilit rol oynar." },
        { n: 17, s: "Cl", name: "Klor", cat: "halogen", desc: "Su arıtma ve dezenfeksiyon işlemlerinde kullanılır." },
        { n: 18, s: "Ar", name: "Argon", cat: "noble", desc: "Ampullerin içini doldurmak için kullanılan asal koruyucudur." },
        { n: 19, s: "K", name: "Potasyum", cat: "alkali", desc: "Sinir iletimi ve kas fonksiyonları için önemlidir." },
        { n: 20, s: "Ca", name: "Kalsiyum", cat: "alkaline", desc: "Kemiklerin ve dişlerin temel yapı taşıdır." },
        { n: 21, s: "Sc", name: "Skandiyum", cat: "transition", desc: "Hafif alaşımlar yapmak için kullanılır; bazen stadyum lambalarında bulunur." },
        { n: 22, s: "Ti", name: "Titanyum", cat: "transition", desc: "Çelik kadar güçlü ama çok daha hafiftir; uçaklarda ve protezlerde kullanılır." },
        { n: 23, s: "V", name: "Vanadyum", cat: "transition", desc: "Çeliği sertleştirmek için kullanılan gümüşi bir metaldir." },
        { n: 24, s: "Cr", name: "Krom", cat: "transition", desc: "Paslanmaz çelik yapımında ve parlak kaplamalarda kullanılır." },
        { n: 25, s: "Mn", name: "Manganez", cat: "transition", desc: "Demir üretim sürecinde oksijeni uzaklaştırmak için hayati önem taşır." },
        { n: 26, s: "Fe", name: "Demir", cat: "transition", desc: "Dünya'nın çekirdeğinin ana bileşenidir ve inşaat sektörünün temel taşıdır." },
        { n: 27, s: "Co", name: "Kobalt", cat: "transition", desc: "Mıknatıs yapımında ve canlı mavi pigmentler oluşturmada kullanılır." },
        { n: 28, s: "Ni", name: "Nikel", cat: "transition", desc: "Madeni paraların yapımında ve korozyona dirençli alaşımlarda bulunur." },
        { n: 29, s: "Cu", name: "Bakır", cat: "transition", desc: "Mükemmel iletkenliği nedeniyle elektrik kablolarının vazgeçilmezidir." },
        { n: 30, s: "Zn", name: "Çinko", cat: "transition", desc: "Demiri paslanmaya karşı korumak için galvanizleme işleminde kullanılır." },
        { n: 31, s: "Ga", name: "Galyum", cat: "transition", desc: "Elde eriyebilen ilginç bir metaldir; LED ve lazerlerde kullanılır." },
        { n: 32, s: "Ge", name: "Germanyum", cat: "metalloid", desc: "Yarı iletken endüstrisinde ve fiber optik kablolarda kilit maddedir." },
        { n: 33, s: "As", name: "Arsenik", cat: "metalloid", desc: "Zehirli özelliğiyle bilinir, ancak lazer ve transistörlerde de kullanılır." },
        { n: 34, s: "Se", name: "Selenyum", cat: "nonmetal", desc: "Işığa duyarlı özellikleri nedeniyle fotokopi makinelerinde kullanılır." },
        { n: 35, s: "Br", name: "Brom", cat: "halogen", desc: "Oda sıcaklığında sıvı halde bulunan tek ametaldir." },
        { n: 36, s: "Kr", name: "Kripton", cat: "noble", desc: "Yüksek yoğunluklu aydınlatma ve fotoğraf flaşlarında kullanılır." },
        { n: 37, s: "Rb", name: "Rubidyum", cat: "alkali", desc: "Hava ile temas eder etmez kendiliğinden tutuşan çok reaktif bir metaldir." },
        { n: 38, s: "Sr", name: "Stronsiyum", cat: "alkaline", desc: "Havai fişeklere parlak kırmızı rengini veren elementtir." },
        { n: 39, s: "Y", name: "İtriyum", cat: "transition", desc: "TV ekranlarında kırmızı renk oluşturmak ve süper iletkenler için kullanılır." },
        { n: 40, s: "Zr", name: "Zirkonyum", cat: "transition", desc: "Nükleer reaktör kılıflarında ve mücevherat (yapay elmas) alanında kullanılır." },
        { n: 41, s: "Nb", name: "Niyobyum", cat: "transition" },
        { n: 42, s: "Mo", name: "Molibden", cat: "transition" },
        { n: 43, s: "Tc", name: "Teknesyum", cat: "transition" },
        { n: 44, s: "Ru", name: "Rutenyum", cat: "transition" },
        { n: 45, s: "Rh", name: "Rodyum", cat: "transition" },
        { n: 46, s: "Pd", name: "Paladyum", cat: "transition" },
        { n: 47, s: "Ag", name: "Gümüş", cat: "transition" },
        { n: 48, s: "Cd", name: "Kadmiyum", cat: "transition" },
        { n: 49, s: "In", name: "İndiyum", cat: "transition" },
        { n: 50, s: "Sn", name: "Kalay", cat: "transition" },
        { n: 51, s: "Sb", name: "Antimon", cat: "metalloid" },
        { n: 52, s: "Te", name: "Tellür", cat: "metalloid" },
        { n: 53, s: "I", name: "İyot", cat: "halogen" },
        { n: 54, s: "Xe", name: "Ksenon", cat: "noble" },
        { n: 55, s: "Cs", name: "Sezyum", cat: "alkali" },
        { n: 56, s: "Ba", name: "Baryum", cat: "alkaline" },
        { n: 57, s: "La", name: "Lantan", cat: "lanthanide" },
        { n: 58, s: "Ce", name: "Seryum", cat: "lanthanide" },
        { n: 59, s: "Pr", name: "Prasedim", cat: "lanthanide" },
        { n: 60, s: "Nd", name: "Neodimyum", cat: "lanthanide" },
        { n: 61, s: "Pm", name: "Prometyum", cat: "lanthanide" },
        { n: 62, s: "Sm", name: "Samaryum", cat: "lanthanide" },
        { n: 63, s: "Eu", name: "Europiyum", cat: "lanthanide" },
        { n: 64, s: "Gd", name: "Gadolinyum", cat: "lanthanide" },
        { n: 65, s: "Tb", name: "Terbiyum", cat: "lanthanide" },
        { n: 66, s: "Dy", name: "Disprozyum", cat: "lanthanide" },
        { n: 67, s: "Ho", name: "Holmiyum", cat: "lanthanide" },
        { n: 68, s: "Er", name: "Erbiyum", cat: "lanthanide" },
        { n: 69, s: "Tm", name: "Tulyum", cat: "lanthanide" },
        { n: 70, s: "Yb", name: "İterbiyum", cat: "lanthanide" },
        { n: 71, s: "Lu", name: "Lutesyum", cat: "lanthanide" },
        { n: 72, s: "Hf", name: "Hafniyum", cat: "transition" },
        { n: 73, s: "Ta", name: "Tantal", cat: "transition" },
        { n: 74, s: "W", name: "Volfram", cat: "transition" },
        { n: 75, s: "Re", name: "Renyum", cat: "transition" },
        { n: 76, s: "Os", name: "Osmiyum", cat: "transition" },
        { n: 77, s: "Ir", name: "İridyum", cat: "transition" },
        { n: 78, s: "Pt", name: "Platin", cat: "transition" },
        { n: 79, s: "Au", name: "Altın", cat: "transition" },
        { n: 80, s: "Hg", name: "Cıva", cat: "transition" },
        { n: 81, s: "Tl", name: "Talyum", cat: "transition" },
        { n: 82, s: "Pb", name: "Kurşun", cat: "transition" },
        { n: 83, s: "Bi", name: "Bizmut", cat: "transition" },
        { n: 84, s: "Po", name: "Polonyum", cat: "metalloid" },
        { n: 85, s: "At", name: "Astatin", cat: "halogen" },
        { n: 86, s: "Rn", name: "Radon", cat: "noble" },
        { n: 87, s: "Fr", name: "Fransiyum", cat: "alkali" },
        { n: 88, s: "Ra", name: "Radyum", cat: "alkaline" },
        { n: 89, s: "Ac", name: "Aktinyum", cat: "actinide" },
        { n: 90, s: "Th", name: "Toryum", cat: "actinide" },
        { n: 91, s: "Pa", name: "Protaktinyum", cat: "actinide" },
        { n: 92, s: "U", name: "Uranyum", cat: "actinide" },
        { n: 93, s: "Np", name: "Neptunyum", cat: "actinide" },
        { n: 94, s: "Pu", name: "Plutonyum", cat: "actinide" },
        { n: 95, s: "Am", name: "Amerikyum", cat: "actinide" },
        { n: 96, s: "Cm", name: "Küriyum", cat: "actinide" },
        { n: 97, s: "Bk", name: "Berkelyum", cat: "actinide" },
        { n: 98, s: "Cf", name: "Kaliforniyum", cat: "actinide" },
        { n: 99, s: "Es", name: "Aynştaynyum", cat: "actinide" },
        { n: 100, s: "Fm", name: "Fermiyum", cat: "actinide" },
        { n: 101, s: "Md", name: "Mendelevyum", cat: "actinide" },
        { n: 102, s: "No", name: "Nobelyum", cat: "actinide" },
        { n: 103, s: "Lr", name: "Lavrensiyum", cat: "actinide" },
        { n: 104, s: "Rf", name: "Rutherfordiyum", cat: "transition" },
        { n: 105, s: "Db", name: "Dubniyum", cat: "transition" },
        { n: 106, s: "Sg", name: "Seaborgiyum", cat: "transition" },
        { n: 107, s: "Bh", name: "Bohriyum", cat: "transition" },
        { n: 108, s: "Hs", name: "Hassiyum", cat: "transition" },
        { n: 109, s: "Mt", name: "Meitneriyum", cat: "transition" },
        { n: 110, s: "Ds", name: "Darmstadtiyum", cat: "transition" },
        { n: 111, s: "Rg", name: "Röntgenyum", cat: "transition" },
        { n: 112, s: "Cn", name: "Kopernikyum", cat: "transition" },
        { n: 113, s: "Nh", name: "Nihonyum", cat: "transition" },
        { n: 114, s: "Fl", name: "Flerovyum", cat: "transition" },
        { n: 115, s: "Mc", name: "Moskovyum", cat: "transition" },
        { n: 116, s: "Lv", name: "Livermoryum", cat: "transition" },
        { n: 117, s: "Ts", name: "Tennessin", cat: "halogen" },
        { n: 118, s: "Og", name: "Oganesson", cat: "noble" }
    ],

    cations: [
        { symbol: 'H⁺', name: 'Hidrojen', charge: '+1', desc: 'Asitliğin temelini oluşturan protondur.' },
        { symbol: 'Li⁺', name: 'Lityum', charge: '+1', desc: 'Lityum pillerinin ana bileşenidir.' },
        { symbol: 'Na⁺', name: 'Sodyum', charge: '+1', desc: 'Vücut sıvılarındaki ana katyondur.' },
        { symbol: 'K⁺', name: 'Potasyum', charge: '+1', desc: 'Hücre içi sinir iletiminde hayati rol oynar.' },
        { symbol: 'NH₄⁺', name: 'Amonyum', charge: '+1', desc: 'Gübre sanayisinde yaygın kullanılan çok atomlu bir iyondur.' },
        { symbol: 'Mg²⁺', name: 'Magnezyum', charge: '+2', desc: 'Klorofilin yapısında bulunur.' },
        { symbol: 'Ca²⁺', name: 'Kalsiyum', charge: '+2', desc: 'Kemik yapısının ana bileşenidir.' },
        { symbol: 'Ba²⁺', name: 'Baryum', charge: '+2', desc: 'X-ışını görüntülemede kontrast maddesi olarak kullanılır.' },
        { symbol: 'Fe²⁺', name: 'Demir (II)', charge: '+2', desc: 'Hemoglobinin yapısında bulunur.' },
        { symbol: 'Fe³⁺', name: 'Demir (III)', charge: '+3', desc: 'Pirit ve hematit gibi cevherlerde bulunur.' },
        { symbol: 'Al³⁺', name: 'Alüminyum', charge: '+3', desc: 'Hafif ve korozyona dayanıklı alaşımlar için kilit iyon.' },
        { symbol: 'Cu⁺', name: 'Bakır (I)', charge: '+1', desc: 'Bakır iyonlarının daha az kararlı halidir.' },
        { symbol: 'Cu²⁺', name: 'Bakır (II)', charge: '+2', desc: 'Çözeltilere mavi renk veren iyon.' },
        { symbol: 'Ag⁺', name: 'Gümüş', charge: '+1', desc: 'Fotoğrafçılık ve ayna üretiminde kullanılır.' },
        { symbol: 'Zn²⁺', name: 'Çinko', charge: '+2', desc: 'Enzim fonksiyonları için önemli bir katyondır.' },
        { symbol: 'Pb²⁺', name: 'Kurşun (II)', charge: '+2', desc: 'Akülerde kullanılan ağır bir metal iyonudur.' },
        { symbol: 'Hg²⁺', name: 'Cıva (II)', charge: '+2', desc: 'Sıvı metal olan cıvanın kararlı iyonudur.' },
        { symbol: 'Sn²⁺', name: 'Kalay (II)', charge: '+2', desc: 'Kalay kaplamacılıkta kullanılır.' },
        { symbol: 'Cr³⁺', name: 'Krom (III)', charge: '+3', desc: 'Metabolizma için esansiyel bir iz elementtir.' }
    ],
    anions: [
        { symbol: 'F⁻', name: 'Florür', charge: '-1', desc: 'Diş minesini güçlendiren iyondur.' },
        { symbol: 'Cl⁻', name: 'Klorür', charge: '-1', desc: 'Mide asidinin ana bileşenidir.' },
        { symbol: 'Br⁻', name: 'Bromür', charge: '-1', desc: 'Eskiden sakinleştirici olarak kullanılırdı.' },
        { symbol: 'I⁻', name: 'İyodür', charge: '-1', desc: 'Tiroit bezinin düzgün çalışması için gereklidir.' },
        { symbol: 'OH⁻', name: 'Hidroksit', charge: '-1', desc: 'Bazik özellik gösteren temel iyondur.' },
        { symbol: 'CN⁻', name: 'Siyanür', charge: '-1', desc: 'Çok zehirli ve sanayide kullanılan bir anyondur.' },
        { symbol: 'NO₃⁻', name: 'Nitrat', charge: '-1', desc: 'Bitki besini olarak gübrelerde bulunur.' },
        { symbol: 'NO₂⁻', name: 'Nitrit', charge: '-1', desc: 'Gıda koruyucusu olarak kullanılır.' },
        { symbol: 'SO₄²⁻', name: 'Sülfat', charge: '-2', desc: 'Sanayide çok yönlü kullanılan bir anyondur.' },
        { symbol: 'SO₃²⁻', name: 'Sülfit', charge: '-2', desc: 'Bazı gıdalarda antioksidan olarak kullanılır.' },
        { symbol: 'CO₃²⁻', name: 'Karbonat', charge: '-2', desc: 'Kireçtaşının ana bileşenidir.' },
        { symbol: 'PO₄³⁻', name: 'Fosfat', charge: '-3', desc: 'DNA ve enerji molekülü ATP\'nin parçasıdır.' },
        { symbol: 'MnO₄⁻', name: 'Permanganat', charge: '-1', desc: 'Güçlü bir yükseltgendir.' },
        { symbol: 'Cr₂O₇²⁻', name: 'Dikromat', charge: '-2', desc: 'Laboratuvarda oksidasyon için kullanılır.' },
        { symbol: 'CH₃COO⁻', name: 'Asetat', charge: '-1', desc: 'Sirkenin içindeki asidin anyonudur.' },
        { symbol: 'ClO⁻', name: 'Hipoklorit', charge: '-1', desc: 'Çamaşır suyunun aktif maddesidir.' },
        { symbol: 'ClO₄⁻', name: 'Perklorat', charge: '-1', desc: 'Roket yakıtlarında oksitleyici olarak kullanılır.' }
    ],
    metals: [
        { symbol: 'Fe', name: 'Demir', desc: 'Dünyanın en çok kullanılan metalidir, inşaat ve araçlarda temel taşıdır.' },
        { symbol: 'Cu', name: 'Bakır', desc: 'Mükemmel bir iletkendir, elektrik kablolarında vazgeçilmezdir.' },
        { symbol: 'Au', name: 'Altın', desc: 'Asla paslanmayan ve çok değerli olan bir soy metaldir.' },
        { symbol: 'Ag', name: 'Gümüş', desc: 'Bilinen en iyi elektrik ve ısı iletkenidir.' },
        { symbol: 'Al', name: 'Alüminyum', desc: 'Hafifliği ve korozyon direnci ile havacılıkta kullanılır.' },
        { symbol: 'Zn', name: 'Çinko', desc: 'Demiri korozyondan korumak için galvanizlemede kullanılır.' },
        { symbol: 'Hg', name: 'Cıva', desc: 'Oda sıcaklığında sıvı halde bulunan tek metaldir.' },
        { symbol: 'Ti', name: 'Titanyum', desc: 'Çok dayanıklı ve vücut dostudur, tıbbi protezlerde kullanılır.' },
        { symbol: 'Pb', name: 'Kurşun', desc: 'Radyasyon kalkanı ve akü yapımında kullanılan ağır bir metaldir.' },
        { symbol: 'Sn', name: 'Kalay', desc: 'Paslanmaya karşı dirençlidir, lehim yapımında kullanılır.' },
        { symbol: 'Pt', name: 'Platin', desc: 'Aşınmaya dirençli, katalizör olarak kullanılan değerli bir metaldir.' },
        { symbol: 'Ni', name: 'Nikel', desc: 'Paslanmaz çelik üretiminde ve madeni paralarda kullanılır.' },
        { symbol: 'Cr', name: 'Krom', desc: 'Sertlik kazandırır, metalleri parlatmak ve korumak için kullanılır.' },
        { symbol: 'Mn', name: 'Manganez', desc: 'Çelik üretiminde oksijen ve kükürt giderici olarak kullanılır.' },
        { symbol: 'W', name: 'Volfram', desc: 'Erime noktası en yüksek olan metaldir, ampul tellerinde kullanılır.' },
        { symbol: 'Na', name: 'Sodyum', desc: 'Yumuşak, gümüş-beyaz renkli, suyla şiddetli reaksiyon veren aktif metal.' },
        { symbol: 'K', name: 'Potasyum', desc: 'Bitki beslenmesi için hayati önem taşıyan çok aktif bir alkali metal.' },
        { symbol: 'Mg', name: 'Magnezyum', desc: 'Hafif alaşımlarda ve fotoğraf makinesi flaşlarında kullanılır.' },
        { symbol: 'Ca', name: 'Kalsiyum', desc: 'Kemiklerin ve dişlerin yapısında bulunan alkali toprak metal.' },
        { symbol: 'Li', name: 'Lityum', desc: 'Pillerde kullanılan, bilinen en hafif katı elementtir.' },
        { symbol: 'Co', name: 'Kobalt', desc: 'Mıknatıs yapımında ve lityum pillerin katotlarında kullanılan önemli bir metaldir.' },
        { symbol: 'Pd', name: 'Paladyum', desc: 'Katalizör olarak kullanılan, hidrojeni emme özelliğiyle bilinen nadir bir metaldir.' },
        { symbol: 'Cd', name: 'Kadmiyum', desc: 'Pillerde ve pigmentlerde kullanılan, ancak zehirli özelliği olan bir metaldir.' },
        { symbol: 'Ba', name: 'Baryum', desc: 'X-ışını kontrast maddelerinde ve havai fişeklere yeşil renk vermede kullanılır.' },
        { symbol: 'Cs', name: 'Sezyum', desc: 'Atom saatlerinde kullanılan, en reaktif kararlı alkali metallerden biridir.' },
        { symbol: 'Fr', name: 'Fransiyum', desc: 'Doğada çok nadir bulunan ve çok kısa ömürlü olan radyoaktif bir alkali metal.' },
        { symbol: 'Ra', name: 'Radyum', desc: 'Marie Curie tarafından keşfedilen, eskiden karanlıkta parlayan boyalar için kullanılan radyoaktif metal.' },
        { symbol: 'U', name: 'Uranyum', desc: 'Nükleer enerji ve savunma sanayisinin temel hammaddesi olan ağır metal.' },
        { symbol: 'Pu', name: 'Plutonyum', desc: 'Nükleer reaktörlerde yakıt veya nükleer silahlarda kullanılan yapay metal.' },
        { symbol: 'Th', name: 'Toryum', desc: 'Gelecekte nükleer yakıt olarak kullanılması planlanan, uranyuma göre daha güvenli bir metal.' },
        { symbol: 'Ga', name: 'Galyum', desc: 'Vücut sıcaklığında (29.7°C) eriyebilen, yarı iletkenlerde kullanılan ilginç bir metal.' },
        { symbol: 'Ge', name: 'Germanyum', desc: 'Transistörlerin icadında rol oynamış, kızılötesi optiklerde kullanılan bir yarı iletkendir.' },
        { symbol: 'In', name: 'İndiyum', desc: 'LCD ekranlarda ve dokunmatik panellerde şeffaf elektrot olarak kullanılır.' },
        { symbol: 'Bi', name: 'Bizmut', desc: 'En az zehirli ağır metaldir; kozmetikte ve ilaçlarda (mide rahatsızlıkları) kullanılır.' },
        { symbol: 'Po', name: 'Polonyum', desc: 'Çok güçlü bir alfa radyasyon kaynağı olan, Curie ailesi tarafından keşfedilen metal.' },
        { symbol: 'Sc', name: 'Skandiyum', desc: 'Yüksek mukavemetli alüminyum alaşımları yapmak için kullanılan hafif bir geçiş metali.' },
        { symbol: 'V', name: 'Vanadyum', desc: 'Çelik alaşımlarına yüksek darbe dayanımı ve esneklik kazandıran gümüşi metal.' },
        { symbol: 'Y', name: 'İtriyum', desc: 'Lazerlerde (YAG) ve TV tüplerinde kırmızı renk oluşturmak için kullanılır.' },
        { symbol: 'Zr', name: 'Zirkonyum', desc: 'Korozyona aşırı dirençli olduğu için nükleer reaktör kılıflarında tercih edilir.' },
        { symbol: 'Nb', name: 'Niyobyum', desc: 'MR cihazlarındaki süper iletken mıknatısların yapımında kullanılan kritik metal.' }
    ],
    first20Elements: [
        { symbol: 'H', name: 'Hidrojen', number: 1, desc: 'Evrenin en bol ve en hafif elementidir.' },
        { symbol: 'He', name: 'Helyum', number: 2, desc: 'Uçan balonlarda kullanılan hafif soygaz.' },
        { symbol: 'Li', name: 'Lityum', number: 3, desc: 'Şarj edilebilir pillerin ana maddesi.' },
        { symbol: 'Be', name: 'Berilyum', number: 4, desc: 'Hafif ama çelikten daha sert olan metal.' },
        { symbol: 'B', name: 'Bor', number: 5, desc: 'Türkiye\'de dünyadaki en büyük rezervi bulunan yarı metal.' },
        { symbol: 'C', name: 'Karbon', number: 6, desc: 'Yaşamın temel taşı, elmas ve grafitin ana maddesi.' },
        { symbol: 'N', name: 'Azot', number: 7, desc: 'Atmosferin %78\'ini oluşturan, soğutmada kullanılan gaz.' },
        { symbol: 'O', name: 'Oksijen', number: 8, desc: 'Solunum için gerekli olan aktif gaz.' },
        { symbol: 'F', name: 'Flor', number: 9, desc: 'En elektronegatif element, diş macunlarında bulunur.' },
        { symbol: 'Ne', name: 'Neon', number: 10, desc: 'Renkli reklam tabelalarında kullanılan soygaz.' },
        { symbol: 'Na', name: 'Sodyum', number: 11, desc: 'Yemek tuzunun ana bileşenlerinden olan aktif metal.' },
        { symbol: 'Mg', name: 'Magnezyum', number: 12, desc: 'Hafif ve beyaz ışık saçarak yanan bir metal.' },
        { symbol: 'Al', name: 'Alüminyum', number: 13, desc: 'Folyo ve mutfak gereçlerinde yaygın kullanılan metal.' },
        { symbol: 'Si', name: 'Silisyum', number: 14, desc: 'Yarı iletken teknolojisinin ve kumun ana maddesi.' },
        { symbol: 'P', name: 'Fosfor', number: 15, desc: 'Kibrit yapımında ve kemik yapısında bulunan ametal.' },
        { symbol: 'S', name: 'Kükürt', number: 16, desc: 'Barut ve sülfürik asit yapımında kullanılan sarı ametal.' },
        { symbol: 'Cl', name: 'Klor', number: 17, desc: 'Suların dezenfeksiyonunda kullanılan zehirli gaz.' },
        { symbol: 'Ar', name: 'Argon', number: 18, desc: 'Ampullerin içinde koruyucu atmosfer oluşturan soygaz.' },
        { symbol: 'K', name: 'Potasyum', number: 19, desc: 'Gübre yapımında ve sinir iletiminde önemli metal.' },
        { symbol: 'Ca', name: 'Kalsiyum', number: 20, desc: 'Mermer ve sütte bulunan, kemik gelişimi için kilit element.' }
    ],
    acidsBases: [
        { symbol: 'HCl', name: 'Hidroklorik Asit (Tuz Ruhu)', charge: 'Asit', desc: 'Midede sindirime yardımcı olan güçlü asit.' },
        { symbol: 'H₂SO₄', name: 'Sülfürik Asit (Zaç Yağı)', charge: 'Asit', desc: 'Sanayinin temel taşı olan en önemli asitlerden biri.' },
        { symbol: 'HNO₃', name: 'Nitrik Asit (Kezzap)', charge: 'Asit', desc: 'Gübre ve patlayıcı üretiminde kullanılan yakıcı asit.' },
        { symbol: 'CH₃COOH', name: 'Asetik Asit (Sirke Ruhu)', charge: 'Asit', desc: 'Zayıf bir asit olup gıdalarda kullanılır.' },
        { symbol: 'H₃PO₄', name: 'Fosforik Asit', charge: 'Asit', desc: 'Gübre üretiminde ve gıda sektöründe asitlik düzenleyici olarak kullanılır.' },
        { symbol: 'H₂CO₃', name: 'Karbonik Asit', charge: 'Asit', desc: 'Gazlı içeceklerde bulunan, karbondioksitin suda çözünmesiyle oluşan zayıf asit.' },
        { symbol: 'HCOOH', name: 'Formik Asit (Karınca Asidi)', charge: 'Asit', desc: 'Doğada karıncaların salgısında bulunan, tekstil ve deri sanayisinde kullanılan asit.' },
        { symbol: 'NaOH', name: 'Sodyum Hidroksit (Sud Kostik)', charge: 'Baz', desc: 'Sabun ve temizlik ürünleri yapımında kullanılan kuvvetli baz.' },
        { symbol: 'KOH', name: 'Potasyum Hidroksit (Potas Kostik)', charge: 'Baz', desc: 'Arap sabunu ve pillerde kullanılan bazdır.' },
        { symbol: 'NH₃', name: 'Amonyak', charge: 'Baz', desc: 'Keskin kokulu, azotlu gübrelerin hammaddesi olan zayıf baz.' },
        { symbol: 'Ca(OH)₂', name: 'Kalsiyum Hidroksit (Sönmüş Kireç)', charge: 'Baz', desc: 'İnşaat ve su arıtma işlemlerinde kullanılır.' },
        { symbol: 'Mg(OH)₂', name: 'Magnezyum Hidroksit (Magnesia Sütü)', charge: 'Baz', desc: 'Mide asidini dengelemek için antiasit olarak kullanılan bazdır.' },
        { symbol: 'Al(OH)₃', name: 'Alüminyum Hidroksit', charge: 'Baz', desc: 'Su arıtma ve mide ilaçlarında kullanılan bir bazik bileşiktir.' }
    ],
    labEquip: [
        { symbol: '🧪', name: 'Beherglas', charge: 'Sıvı Karıştırma', desc: 'Çözelti hazırlama ve karıştırma için kullanılır.' },
        { symbol: '⚗️', name: 'Erlenmayer', charge: 'Saklama/Çalkalama', desc: 'Ağzının dar olması sayesinde sıvıların çalkalanması ve saklanması için idealdir.' },
        { symbol: '🌡️', name: 'Dereceli Silindir', charge: 'Hacim Ölçümü', desc: 'Sıvıların hacmini hassas ölçmek için kullanılır.' },
        { symbol: '🔥', name: 'Bunzen Beki', charge: 'Isıtma', desc: 'Laboratuvarda kontrol edilebilir alev kaynağıdır.' },
        { symbol: '📏', name: 'Büret', charge: 'Titrasyon', desc: 'Hacim analizi (titrasyon) işlemlerinde kullanılır.' },
        { symbol: '⚖️', name: 'Analitik Terazi', charge: 'Hassas Tartım', desc: 'Kütleyi çok yüksek hassasiyetle ölçer.' },
        { symbol: '🥣', name: 'Havan', charge: 'Ezme/Öğütme', desc: 'Katı maddeleri toz haline getirmek için kullanılan porselen kap.' },
        { symbol: '🔬', name: 'Ayırma Hunisi', charge: 'Ayırma', desc: 'Birbiriyle karışmayan sıvıları (zeytinyağı-su gibi) ayırmak için kullanılır.' },
        { symbol: '🥢', name: 'Spatül', charge: 'Madda Taşıma', desc: 'Toz halindeki kimyasalları tartım veya aktarım sırasında almak için kullanılır.' },
        { symbol: '🍵', name: 'Saat Camı', charge: 'Kurutma/Tartım', desc: 'Az miktardaki katıların kurutulması veya tartılması için kullanılır.' }
    ],
    quizQuestions: [
        { q: "Doğada atomik yapıda bulunan elementler hangileridir?", a: "Soygazlar", options: ["Halojenler", "Metaller", "Soygazlar", "Ametaller"] },
        { q: "Hangisi oda koşullarında gaz halindedir?", a: "Klor", options: ["İyot", "Brom", "Klor", "Karbon"] },
        { q: "Bir atomun çekirdek yükü neye eşittir?", a: "Proton Sayısı", options: ["Nötron Sayısı", "Elektron Sayısı", "Proton Sayısı", "Kütle Numarası"] },
        { q: "Aşağıdakilerden hangisi bir kimyasal değişimdir?", a: "Ekmeğin Küflenmesi", options: ["Buzun Erimesi", "Şekerin Suda Çözünmesi", "Ekmeğin Küflenmesi", "Camın Kırılması"] },
        { q: "Kovalent bağlı bileşiklerin en küçük yapı birimi nedir?", a: "Molekül", options: ["Atom", "Molekül", "İyon", "Kristal"] },
        { q: "Hangi elementin elektronegatifliği en düşüktür?", a: "Sezyum", options: ["Flor", "Oksijen", "Sezyum", "Fransiyum"] },
        { q: "Asitlerin pH değeri hangi aralıktadır?", a: "0 - 7", options: ["0 - 7", "7 - 14", "Sadece 7", "0 - 14"] },
        { q: "Sönmüş kirecin formülü hangisidir?", a: "Ca(OH)₂", options: ["CaO", "CaCO₃", "Ca(OH)₂", "CaCl₂"] },
        { q: "Hangisi bir homojen karışımdır?", a: "Hava", options: ["Çamurlu Su", "Süt", "Hava", "Zeytinyağı-Su"] },
        { q: "Ametaller periyodik tablonun hangi tarafında toplanmıştır?", a: "Sağ", options: ["Sol", "Sağ", "Alt", "Orta"] },
        { q: "Sıvıların yüzey gerilimini azaltan maddelere ne denir?", a: "Sürfaktan", options: ["Katalizör", "Sürfaktan", "İndikatör", "Emülgatör"] },
        { q: "Hangisi bir soygazın elektron dizilimine benzemez?", a: "Na", options: ["He", "Ne", "Ar", "Na"] },
        { q: "Amoyağın (NH₃) molekül şekli hangisidir?", a: "Üçgen Piramit", options: ["Doğrusal", "Üçgen Piramit", "Düzgün Dörtyüzlü", "Kırık Doğru"] },
        { q: "Hangi kanun Lavoisier tarafından bulunmuştur?", a: "Kütlenin Korunumu", options: ["Sabit Oranlar", "Katlı Oranlar", "Kütlenin Korunumu", "İdeal Gaz"] },
        { q: "Etanolün (alkol) formülü hangisidir?", a: "C₂H₅OH", options: ["CH₃OH", "C₂H₅OH", "CH₃COOH", "C₃H₇OH"] },
        { q: "Nötr bir atomda proton sayısı neye eşittir?", a: "Elektron Sayısı", options: ["Nötron Sayısı", "Elektron Sayısı", "Kütle Numarası", "Yörünge Sayısı"] },
        { q: "Atom çapı periyodik tabloda nasıl değişir?", a: "Aşağı doğru artar", options: ["Sağa doğru artar", "Aşağı doğru artar", "Sabit kalır", "Yukarı doğru artar"] },
        { q: "Hangi gaz ozon tabakasına zarar verir?", a: "CFC", options: ["O₂", "CFC", "N₂", "Ar"] },
        { q: "Buzun yoğunluğu suyun yoğunluğundan neden azdır?", a: "Hidrojen Bağları", options: ["İyonik Bağlar", "Hidrojen Bağları", "Metalik Bağlar", "Kovalent Bağlar"] },
        { q: "Kalsiyum karbonatın yaygın adı nedir?", a: "Kireç Taşı", options: ["Sönmüş Kireç", "Kireç Taşı", "Alçı Taşı", "Yemek Sodası"] },
        { q: "Hangisi bir metalin özelliğidir?", a: "Isı ve elektriği iyi iletmesi", options: ["Kırılgan olması", "Isı ve elektriği iyi iletmesi", "Mat görünümlü olması", "Gaz halde olması"] },
        { q: "Elementler sembollerle gösterilirken hangisi kuraldır?", a: "İlk harf daima büyük", options: ["Hepsi küçük", "İlk harf daima büyük", "Hepsi büyük", "Rakam kullanılmalı"] },
        { q: "Sülfüriz asidin (H₂SO₄) tesir değerliği kaçtır?", a: "2", options: ["1", "2", "3", "0"] },
        { q: "Hangisi simyacıların keşfettiği bir malzemedir?", a: "İmbik", options: ["Laboratuvar Terazisi", "İmbik", "Spektroskop", "Elektron Mikroskobu"] },
        { q: "Sodyumun sembolü hangisidir?", a: "Na", options: ["S", "So", "Na", "Sn"] },
        { q: "Gazların basıncı ne ile ölçülür?", a: "Manometre", options: ["Barometre", "Manometre", "Termometre", "Kalorimetre"] },
        { q: "Hidrojen bağının oluşması için H atomu hangi elemente bağlı olmalıdır?", a: "F, O veya N", options: ["C, S veya P", "F, O veya N", "Cl, Br veya I", "K, Na veya Li"] },
        { q: "Hangisi bir bazdır?", a: "NaOH", options: ["HCl", "NaOH", "H₂SO₄", "CO₂"] },
        { q: "Karışımları ayırmak için 'Ayrımsal Damıtma' neye göre yapılır?", a: "Kaynama Noktası", options: ["Yoğunluk", "Kaynama Noktası", "Çözünürlük", "Erime Noktası"] },
        { q: "Hangisi kovalent bağlı bir bileşiktir?", a: "CO₂", options: ["NaCl", "MgO", "CO₂", "KI"] },
        { q: "Atomik kütle birimi (akb) neye göre hesaplanır?", a: "Karbon-12 isotopu", options: ["Hidrojen-1", "Karbon-12 isotopu", "Oksijen-16", "Azot-14"] },
        { q: "Hangi metal oda koşullarında parlar?", a: "Hepsi (Temizlendiklerinde)", options: ["Hepsi (Temizlendiklerinde)", "Sadece Altın", "Sadece Gümüş", "Hiçbiri"] },
        { q: "Polimerleşme tepkimesi sonucu ne oluşur?", a: "Plastik", options: ["Tuz", "Su", "Plastik", "Karbon"] },
        { q: "Hangisi bir radyoaktif maddedir?", a: "Radyum", options: ["Demir", "Bakır", "Radyum", "Altın"] },
        { q: "Ametallerin elektron alma isteğine ne denir?", a: "Elektronegatiflik", options: ["Atom Çapı", "İyonlaşma Enerjisi", "Elektronegatiflik", "Metalik Özellik"] },
        { q: "Hangi element güneşin ana bileşenidir?", a: "Hidrojen", options: ["Helyum", "Hidrojen", "Oksijen", "Karbon"] },
        { q: "Suyun elektrolizi sonucu hangi gazlar açığa çıkar?", a: "H₂ ve O₂", options: ["H₂ ve O₂", "H₂O ve CO₂", "N₂ ve O₂", "H₂ ve N₂"] },
        { q: "İyonik bağ nasıl oluşur?", a: "Elektron alışverişi ile", options: ["Elektron ortaklaşması ile", "Elektron alışverişi ile", "Proton transferi ile", "Nötron etkileşimi ile"] },
        { q: "Amonyum klorürün (NH₄Cl) yaygın adı nedir?", a: "Nişadır", options: ["Güherçile", "Nişadır", "Kezzap", "Sirke Ruhu"] },
        { q: "Hangisi bir adsorbsiyon olayıdır?", a: "Gaz maskelerinin gazı tutması", options: ["Buzun erimesi", "Tuzun çözünmesi", "Gaz maskelerinin gazı tutması", "Demirin paslanması"] },
        { q: "En küçük atom numaralı element hangisidir?", a: "Hidrojen", options: ["Helyum", "Hidrojen", "Lityum", "Bor"] },
        { q: "Hangisi yanıcı bir gazdır?", a: "Metan", options: ["Helyum", "Metan", "Neon", "Karbondioksit"] },
        { q: "Periyodik tabloda dikey sütunlara ne denir?", a: "Grup", options: ["Periyot", "Grup", "Blok", "Yörünge"] },
        { q: "Asitlerin tadı nasıldır?", a: "Ekşi", options: ["Tatlı", "Ekşi", "Acı", "Tuzlu"] },
        { q: "Hangisi yapay bir liftir?", a: "Naylon", options: ["Pamuk", "İpek", "Yün", "Naylon"] },
        { q: "Altının sembolü hangisidir?", a: "Au", options: ["Ag", "Au", "Al", "At"] },
        { q: "Hangisi bir süblimleşme örneğidir?", a: "Naftalin", options: ["Su", "Alkol", "Naftalin", "Cıva"] },
        { q: "Demir (II) oksit bileşiğinin formülü hangisidir?", a: "FeO", options: ["Fe₂O₃", "FeO", "Fe₃O₄", "FeO₂"] },
        { q: "Hava bir nevi nedir?", a: "Homojen Karışım", options: ["Bileşik", "Element", "Homojen Karışım", "Heterojen Karışım"] },
        { q: "En kararlı element grubu hangisidir?", a: "Soygazlar", options: ["Alkali Metaller", "Halojenler", "Soygazlar", "Geçiş Metalleri"] },
        { q: "H₂O molekülünde bağlar arası açı yaklaşık kaçtır?", a: "104.5°", options: ["90°", "180°", "120°", "104.5°"] },
        { q: "Hangisi bir emülsiyondur?", a: "Mayonez", options: ["Süt", "Mayonez", "Hava", "Duman"] },
        { q: "Tuzlu suyun buharlaştırılması hangi ayırma tekniğidir?", a: "Kristallendirme", options: ["Süzme", "Kristallendirme", "Damıtma", "Eleme"] },
        { q: "Sabit sıcaklıkta gazın basıncı hacmiyle ters orantılıdır diyen kimdir?", a: "Boyle", options: ["Charles", "Boyle", "Gay-Lussac", "Avogadro"] },
        { q: "Hangisi bir karbon allotropudur?", a: "Fulleren", options: ["Fulleren", "Karbondioksit", "Metan", "Su"] },
        { q: "Hangisi oda sıcaklığında sıvı metaldir?", a: "Cıva", options: ["Demir", "Cıva", "Bakır", "Altın"] },
        { q: "Asetonun IUPAC adı nedir?", a: "Propanon", options: ["Metanal", "Propanon", "Etanol", "Butanon"] },
        { q: "Kirecin söndürülmesi nasıl bir tepkimedir?", a: "Ekzotermik", options: ["Endotermik", "Ekzotermik", "Analiz", "İzotermik"] },
        { q: "Hangi element bitkilerde fotosentez için gereklidir?", a: "Magnezyum", options: ["Demir", "Altın", "Magnezyum", "Gümüş"] },
        { q: "Laboratuvarda göz yakıcı gazlardan korunmak için ne kullanılır?", a: "Peker ocak", options: ["Büret", "Peker ocak", "Çeker ocak", "Desikatör"] },
        { q: "Hangisi bir antioksidandır?", a: "C Vitamini", options: ["Tuz", "C Vitamini", "Sirke", "Klor"] },
        { q: "Maden suları hangi sınıfa girer?", a: "Çözelti", options: ["Emülsiyon", "Süspansiyon", "Aerosol", "Çözelti"] },
        { q: "Hangisi zayıf bir bazdır?", a: "Amonyak", options: ["NaOH", "KOH", "Amonyak", "LiOH"] },
        { q: "Periyodik tabloda atom numarası 8 olan element hangisidir?", a: "Oksijen", options: ["Azot", "Oksijen", "Flor", "Karbon"] },
        { q: "Hangisi bir bileşiktir?", a: "Glikoz", options: ["Hava", "Deniz Suyu", "Glikoz", "Çelik"] },
        { q: "Gümüşün (Ag) atom numarası nedir?", a: "47", options: ["47", "79", "80", "13"] },
        { q: "Kükürt dioksitin formülü hangisidir?", a: "SO₂", options: ["SO₃", "SO₂", "S₂O", "SO₄"] },
        { q: "Sodyum hidroksitin yaygın adı nedir?", a: "Sud-kostik", options: ["Sud-kostik", "Potas-kostik", "Yemek Sodası", "Nişadır"] },
        { q: "Hangi element kemik ve diş yapısında bulunur?", a: "Kalsiyum", options: ["Magnezyum", "Kalsiyum", "Sodyum", "Potasyum"] },
        { q: "Hangisi bir fiziksel değişimdir?", a: "Buzun Erimesi", options: ["Sütün Ekşimesi", "Kağıdın Yanması", "Buzun Erimesi", "Demirin Paslanması"] },
        { q: "Azot (N₂) molekülünde kaç tane kovalent bağ vardır?", a: "3", options: ["1", "2", "3", "0"] },
        { q: "Hangisi simyacıların temel amacıydı?", a: "Ölümsüzlük iksirini bulmak", options: ["Elektriği bulmak", "Ölümsüzlük iksirini bulmak", "Uçak yapmak", "İnterneti bulmak"] },
        { q: "Hangi gaz yangın söndürücülerde kullanılır?", a: "CO₂", options: ["O₂", "CO₂", "H₂", "N₂"] },
        { q: "Metallerin yüzeyleri neden parlaktır?", a: "Serbest elektronlar ışığı yansıtır", options: ["Çok sert oldukları için", "Işığı soğurdukları için", "Serbest elektronlar ışığı yansıtır", "Düzgün atom dizilişi"] },
        { q: "Hidroklorik asidin pH değeri yaklaşık kaçtır?", a: "1-2", options: ["1-2", "7", "12", "14"] },
        { q: "İyonlaşma enerjisi en yüksek element hangisidir?", a: "Helyum", options: ["Flor", "Fransiyum", "Helyum", "Sezyum"] },
        { q: "Hangisi bir soylu metaldir?", a: "Altın", options: ["Demir", "Bakır", "Altın", "Alüminyum"] },
        { q: "Güneş kremlerinde kullanılan koruyucu madde hangisidir?", a: "Çinko Oksit", options: ["NaCl", "Çinko Oksit", "Şeker", "Alkol"] },
        { q: "Suların sertliği neye bağlıdır?", a: "Kalsiyum ve Magnezyum iyonlarına", options: ["Sodyum miktarına", "Kalsiyum ve Magnezyum iyonlarına", "Sıcaklığa", "Tuz miktarına"] },
        { q: "Hangisi bir asit yağmuru sebebidir?", a: "SO₂ ve NO₂ gazları", options: ["O₂ gazı", "CO₂ gazı", "SO₂ ve NO₂ gazları", "Helyum"] },
        { q: "Sabun elden neden kayar?", a: "Bazik özellikten dolayı", options: ["Asidik özellikten dolayı", "Bazik özellikten dolayı", "Nötr olduğu için", "Sıvı olduğu için"] },
        { q: "Elementler neye göre sıralanmıştır?", a: "Atom Numarası", options: ["Kütle Numarası", "Atom Numarası", "Yörünge Sayısı", "Alfabetik Sıra"] },
        { q: "Hangisi bir sentetik polimerdir?", a: "Teflon", options: ["Pamuk", "İpek", "Teflon", "Kauçuk"] },
        { q: "Aspirinin ana hammaddesi nedir?", a: "Salisilik Asit", options: ["Sirke", "Alkol", "Salisilik Asit", "Tuz"] },
        { q: "Hangisi bir alkali metaldir?", a: "Lityum", options: ["Magnezyum", "Lityum", "Alüminyum", "Bakır"] },
        { q: "Demir (III) klorür formülü hangisidir?", a: "FeCl₃", options: ["FeCl₂", "FeCl₃", "Fe₂Cl₃", "FeCl"] },
        { q: "Atom çapı en büyük olan hangisidir?", a: "Potasyum", options: ["Sodyum", "Potasyum", "Magnezyum", "Alüminyum"] },
        { q: "Hangisi kovalent bir katıdır?", a: "Elmas", options: ["Tuz", "Buz", "Elmas", "Demir"] },
        { q: "Suyun donma noktası dış basınç artarsa nasıl değişir?", a: "Düşer", options: ["Artar", "Düşer", "Değişmez", "Önce artar sonra düşer"] },
        { q: "Karınca asidi olarak bilinen asit hangisidir?", a: "Formik Asit", options: ["Asetik Asit", "Sülfürik Asit", "Formik Asit", "Nitrik Asit"] },
        { q: "Hangisi havadan hafiftir?", a: "Hidrojen", options: ["Azot", "Hidrojen", "Oksijen", "Metan"] },
        { q: "Davy lambası nerede kullanılır?", a: "Madenlerde", options: ["Laboratuvarlarda", "Madenlerde", "Uzayda", "Hastanelerde"] },
        { q: "Hangisi bir indikatör değildir?", a: "Etil Alkol", options: ["Fenolftalein", "Metil Oranj", "Turnusol", "Etil Alkol"] },
        { q: "Nötralizasyon tepkimesi sonucu ne oluşur?", a: "Tuz ve Su", options: ["Sadece Tuz", "Tuz ve Su", "Asit ve Baz", "Gaz"] },
        { q: "Çamaşır sodasının formülü hangisidir?", a: "Na₂CO₃", options: ["NaHCO₃", "Na₂CO₃", "NaOH", "NaCl"] },
        { q: "Hangisi bir halojendir?", a: "İyot", options: ["Neon", "Azot", "İyot", "Kalsiyum"] },
        { q: "Atom modeli teorisini ilk atan kimdir?", a: "Democritus", options: ["Dalton", "Thomson", "Democritus", "Rutherford"] },
        { q: "Hücre zarının temel yapısı hangisidir?", a: "Fosfolipit", options: ["Glikoz", "Fosfolipit", "Tuz", "Su"] },
        { q: "Buzdolabı gazı olarak bilinen gaz grubu hangisidir?", a: "Freon", options: ["Neon", "Oksijen", "Freon", "Metan"] },
        { q: "Yemek sodasının (NaHCO₃) kimyasal adı nedir?", a: "Sodyum Bikarbonat", options: ["Sodyum Karbonat", "Sodyum Bikarbonat", "Kalsiyum Karbonat", "Sodyum Klorür"] },
        { q: "Hangi metal oda sıcaklığında vücut ısısıyla eriyebilir?", a: "Galyum", options: ["Cıva", "Altın", "Galyum", "Gümüş"] },
        { q: "Mide asidini dengelemek için kullanılan 'Magnesia Sütü' hangi bazdır?", a: "Mg(OH)₂", options: ["NaOH", "KOH", "Mg(OH)₂", "Ca(OH)₂"] },
        { q: "MR cihazlarında süper iletken mıknatıslar için kullanılan metal hangisidir?", a: "Niyobyum", options: ["Demir", "Bakır", "Niyobyum", "Altın"] },
        { q: "Kireç taşının formülü hangisidir?", a: "CaCO₃", options: ["CaO", "Ca(OH)₂", "CaCO₃", "CaCl₂"] },
        { q: "Hangi radyoaktif element Marie Curie tarafından keşfedilmiştir?", a: "Radyum", options: ["Uranyum", "Plutonyum", "Radyum", "Demir"] },
        { q: "Barut yapımında ve gübrede kullanılan 'Güherçile' hangisidir?", a: "KNO₃", options: ["NaCl", "KNO₃", "NH₄Cl", "AgNO₃"] },
        { q: "LCD ekranlarda şeffaf elektrot olarak kullanılan metal hangisidir?", a: "İndiyum", options: ["Alüminyum", "Bakır", "İndiyum", "Çinko"] },
        { q: "Karınca asidi olarak bilinen asit hangisidir?", a: "Formik Asit", options: ["Sülfürik Asit", "Asetik Asit", "Formik Asit", "Nitrik Asit"] },
        { q: "Hangi metal nükleer reaktör kılıflarında korozyon direnci için kullanılır?", a: "Zirkonyum", options: ["Kurşun", "Demir", "Zirkonyum", "Bakır"] },
        { q: "Nişadırın kimyasal formülü nedir?", a: "NH₄Cl", options: ["NaCl", "NH₄Cl", "KCl", "LiCl"] },
        { q: "Gelecekte daha güvenli nükleer yakıt olması planlanan element hangisidir?", a: "Toryum", options: ["Uranyum", "Plutonyum", "Toryum", "Radyum"] },
        { q: "En az zehirli ağır metal hangisidir?", a: "Bizmut", options: ["Kurşun", "Cıva", "Bizmut", "Kadmiyum"] },
        { q: "Gazlı içeceklerde asitlik veren madde hangisidir?", a: "Karbonik Asit", options: ["Hidroklorik Asit", "Karbonik Asit", "Sülfürik Asit", "Nitrik Asit"] },
        { q: "Hangi element güneş panellerinde yarı iletken olarak kullanılır?", a: "Silisyum", options: ["Karbon", "Demir", "Silisyum", "Bakır"] },
        { q: "Mıknatıs yapımında kullanılan geçiş metali hangisidir?", a: "Kobalt", options: ["Bakır", "Altın", "Kobalt", "Gümüş"] },
        { q: "Etil alkolün formülü hangisidir?", a: "C₂H₅OH", options: ["CH₃OH", "C₂H₅OH", "C₃H₇OH", "CH₃COOH"] },
        { q: "Göz taşı olarak bilinen bileşik hangisidir?", a: "CuSO₄", options: ["FeSO₄", "ZnSO₄", "CuSO₄", "MgSO₄"] },
        { q: "Hangi asit gübre üretiminde ve kolalarda asitlik düzenleyici olarak kullanılır?", a: "Fosforik Asit", options: ["Nitrik Asit", "Fosforik Asit", "Hidroklorik Asit", "Asetik Asit"] },
        { q: "Laboratuvarda birbiriyle karışmayan sıvıları ayırmak için ne kullanılır?", a: "Ayırma Hunisi", options: ["Beherglas", "Büret", "Ayırma Hunisi", "Pipet"] },
        { q: "Toz kimyasalları taşımak için kullanılan metal veya plastik kaşığa ne denir?", a: "Spatül", options: ["Büret", "Spatül", "Pipet", "Havan"] },
        { q: "Katı maddeleri toz haline getirmek için kullanılan porselen araç hangisidir?", a: "Havan", options: ["Beher", "Havan", "Erlenmayer", "Saat Camı"] }
    ],
    titles: [
        { score: 0, title: "Çaylak" },
        { score: 1000, title: "Atom Avcısı" },
        { score: 2500, title: "Karışım Ustası" },
        { score: 5000, title: "Elektron Efendisi" },
        { score: 10000, title: "Süper Simyacı" },
        { score: 25000, title: "Bilim Efsanesi" }
    ],
    vipTitles: [
        { score: 0, title: "V.I.P Prenses 👑" },
        { score: 1000, title: "Kelebek Kraliçesi 🦋" },
        { score: 2500, title: "Sihirli Simyacı ✨" },
        { score: 5000, title: "Elmas Deha 💎" },
        { score: 10000, title: "Bilim Tanrıçası 💖" }
    ],
    avatars: [
        'school_logo.jpg',
        'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
        'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka',
        'https://api.dicebear.com/7.x/avataaars/svg?seed=Caleb',
        'https://api.dicebear.com/7.x/avataaars/svg?seed=Sasha',
        'https://api.dicebear.com/7.x/avataaars/svg?seed=Jasper',
        'https://api.dicebear.com/7.x/avataaars/svg?seed=Willow'
    ],
    vipAvatars: [
        'vip_1.png', // Kimyager Prenses
        'vip_2.png', // Zarif Bilim Kızı
        'vip_3.png', // Modern Prenses
        'vip_4.png', // Kristal Deha
        'vip_5.png'  // Kraliyet Asistanı
    ],
    badges: [
        { id: 'b_caylak', name: 'Bilim Yolcusu', desc: '100 puana ulaştın!', icon: 'fa-walking' },
        { id: 'b_ilk_oyun', name: 'Deney Başladı', desc: 'İlk oyununu tamamladın!', icon: 'fa-flask' },
        { id: 'b_combo_5', name: 'Hızlı Reaksiyon', desc: '5x Combo yaptın!', icon: 'fa-bolt' },
        { id: 'b_combo_15', name: 'Atom Parçalayıcı', desc: '15x Combo yaptın!', icon: 'fa-atom' },
        { id: 'b_quiz_master', name: 'Quiz Master', desc: '10 quiz sorusunu doğru bil.', icon: 'fa-brain' },
        { id: 'b_asit_uzmani', name: 'Asitlerin Efendisi', desc: 'Asit/Baz oyununda uzmanlaştın.', icon: 'fa-vial-circle-check' },
        { id: 'b_profesor', name: 'Kimya Profesörü', desc: '500 puana ulaştın!', icon: 'fa-graduation-cap' },
        { id: 'b_lab_faresi', name: 'Laboratuvar Faresi', desc: '50 oyun tamamladın!', icon: 'fa-microscope' },
        { id: 'b_legend', name: 'Bilim Efsanesi', desc: '1000 puan barajını aştın!', icon: 'fa-crown' },
        { id: 'b_nobel', name: 'Nobel Yolcusu', desc: 'Zor modda kusursuz galibiyet!', icon: 'fa-award' },
        { id: 'b_simyaci', name: 'Büyük Simyacı', desc: '50,000 toplama puana ulaştın!', icon: 'fa-wand-magic-sparkles' }
    ],
    levels: [
        { title: 'Çaylak', requiredScore: 0 },
        { title: 'Asistan', requiredScore: 500 },
        { title: 'Uzman', requiredScore: 1500 },
        { title: 'Bilgin', requiredScore: 3000 },
        { title: 'Deha', requiredScore: 7000 },
        { title: 'Nobel Adayı', requiredScore: 15000 }
    ],
    compounds: [
        { symbol: 'NaCl', name: 'Yemek Tuzu (Sodyum Klorür)', desc: 'Sofra tuzu olarak bilinir, gıdaları korumak ve tatlandırmak için kullanılır.' },
        { symbol: 'CaCO₃', name: 'Kireç Taşı (Kalsiyum Karbonat)', desc: 'İnşaat malzemesi, tebeşir ve mermerin ana bileşenidir.' },
        { symbol: 'NaHCO₃', name: 'Yemek Sodası (Sodyum Bikarbonat)', desc: 'Hamur işlerinde kabartma tozu olarak kullanılır.' },
        { symbol: 'NH₄Cl', name: 'Nişadır (Amonyum Klorür)', desc: 'Pillerde, lehimlemede ve bazı öksürük şuruplarında bulunur.' },
        { symbol: 'CaO', name: 'Sönmemiş Kireç (Kalsiyum Oksit)', desc: 'Sanayide, özellikle çimento ve cam üretiminde yaygın kullanılır.' },
        { symbol: 'Ca(OH)₂', name: 'Sönmüş Kireç (Kalsiyum Hidroksit)', desc: 'Badana yapımında ve su arıtma işlemlerinde kullanılır.' },
        { symbol: 'CuSO₄', name: 'Göz Taşı (Bakır (II) Sülfat)', desc: 'Tarımda fungusit (mantar öldürücü) olarak kullanılır.' },
        { symbol: 'KNO₃', name: 'Güherçile (Potasyum Nitrat)', desc: 'Barut yapımında ve gübre sektöründe kullanılan oksitleyici bir maddedir.' },
        { symbol: 'CH₃OH', name: 'Metil Alkol (Odun Alkolü)', desc: 'Çok zehirlidir, endüstride çözücü olarak kullanılır.' },
        { symbol: 'C₂H₅OH', name: 'Etil Alkol', desc: 'Dezenfektanlarda ve içeceklerde kullanılan alkol türüdür.' },
        { symbol: 'C₆H₁₂O₆', name: 'Glikoz (Şeker)', desc: 'Canlıların temel enerji kaynağı olan basit bir şekerdir.' },
        { symbol: 'H₂O', name: 'Su', desc: 'Yaşamın temel sıvısı, en yaygın çözücüdür.' },
        { symbol: 'CO₂', name: 'Karbondioksit', desc: 'Solunum sonucu dışarı atılan gazdır, kuru buz bunun katı halidir.' }
    ],
    fusionQuestions: [
        { s: 'H', n: 'Hidrojen' }, { s: 'He', n: 'Helyum' }, { s: 'Li', n: 'Lityum' }, { s: 'Be', n: 'Berilyum' },
        { s: 'B', n: 'Bor' }, { s: 'C', n: 'Karbon' }, { s: 'N', n: 'Azot' }, { s: 'O', n: 'Oksijen' },
        { s: 'F', n: 'Flor' }, { s: 'Ne', n: 'Neon' }, { s: 'Na', n: 'Sodyum' }, { s: 'Mg', n: 'Magnezyum' },
        { s: 'Al', n: 'Alüminyum' }, { s: 'Si', n: 'Silisyum' }, { s: 'P', n: 'Fosfor' }, { s: 'S', n: 'Kükürt' },
        { s: 'Cl', n: 'Klor' }, { s: 'Ar', n: 'Argon' }, { s: 'K', n: 'Potasyum' }, { s: 'Ca', n: 'Kalsiyum' },
        { s: 'NaCl', n: 'Sodyum Klorür' }, { s: 'CaCO₃', n: 'Kalsiyum Karbonat' }, { s: 'H₂O', n: 'Su' },
        { s: 'NH₄Cl', n: 'Amonyum Klorür' }, { s: 'NaHCO₃', n: 'Sodyum Bikarbonat' }, { s: 'CaO', n: 'Kalsiyum Oksit' },
        { s: 'CuSO₄', n: 'Bakır (II) Sülfat' }, { s: 'KNO₃', n: 'Potasyum Nitrat' }, { s: 'CO₂', n: 'Karbondioksit' },
        { s: 'Sc', n: 'Skandiyum' }, { s: 'Ti', n: 'Titanyum' }, { s: 'V', n: 'Vanadyum' }, { s: 'Cr', n: 'Krom' },
        { s: 'Mn', n: 'Manganez' }, { s: 'Fe', n: 'Demir' }, { s: 'Co', n: 'Kobalt' }, { s: 'Ni', n: 'Nikel' },
        { s: 'Cu', n: 'Bakır' }, { s: 'Zn', n: 'Çinko' }, { s: 'Ga', n: 'Galyum' }, { s: 'Ge', n: 'Germanyum' },
        { s: 'As', n: 'Arsenik' }, { s: 'Se', n: 'Selenyum' }, { s: 'Br', n: 'Brom' }, { s: 'Kr', n: 'Kripton' },
        { s: 'Ag', n: 'Gümüş' }, { s: 'Au', n: 'Altın' }, { s: 'Hg', n: 'Cıva' }, { s: 'Pb', n: 'Kurşun' },
        { s: 'Sn', n: 'Kalay' }, { s: 'W', n: 'Volfram' }, { s: 'Pt', n: 'Platin' }, { s: 'U', n: 'Uranyum' },
        { s: 'NH₄⁺', n: 'Amonyum' }, { s: 'OH⁻', n: 'Hidroksit' }, { s: 'NO₃⁻', n: 'Nitrat' }, { s: 'SO₄²⁻', n: 'Sülfat' },
        { s: 'CO₃²⁻', n: 'Karbonat' }, { s: 'PO₄³⁻', n: 'Fosfat' }, { s: 'CN⁻', n: 'Siyanür' }, { s: 'MnO₄⁻', n: 'Permanganat' },
        { s: 'CH₃COO⁻', n: 'Asetat' }, { s: 'Cl⁻', n: 'Klorür' }, { s: 'F⁻', n: 'Florür' }, { s: 'Br⁻', n: 'Bromür' },
        { s: 'I⁻', n: 'İyodür' }, { s: 'S²⁻', n: 'Sülfür' }, { s: 'N³⁻', n: 'Nitrür' }, { s: 'O²⁻', n: 'Oksit' },
        { s: 'H⁺', n: 'Hidrojen iyonu' }, { s: 'Li⁺', n: 'Lityum iyonu' }, { s: 'Na⁺', n: 'Sodyum iyonu' }, { s: 'K⁺', n: 'Potasyum iyonu' },
        { s: 'Mg²⁺', n: 'Magnezyum iyonu' }, { s: 'Ca²⁺', n: 'Kalsiyum iyonu' }, { s: 'Ba²⁺', n: 'Baryum iyonu' }, { s: 'Al³⁺', n: 'Alüminyum iyonu' },
        { s: 'Zn²⁺', n: 'Çinko iyonu' }, { s: 'Fe²⁺', n: 'Demir (II) iyonu' }, { s: 'Fe³⁺', n: 'Demir (III) iyonu' }, { s: 'Cu⁺', n: 'Bakır (I) iyonu' },
        { s: 'Cu²⁺', n: 'Bakır (II) iyonu' }, { s: 'Ag⁺', n: 'Gümüş iyonu' }, { s: 'Hg²⁺', n: 'Cıva (II) iyonu' }, { s: 'Pb²⁺', n: 'Kurşun (II) iyonu' },
        { s: 'HCO₃⁻', n: 'Bikarbonat' }, { s: 'HSO₄⁻', n: 'Bisülfat' }, { s: 'ClO⁻', n: 'Hipoklorit' }, { s: 'ClO₂⁻', n: 'Klorit' },
        { s: 'ClO₃⁻', n: 'Klorat' }, { s: 'ClO₄⁻', n: 'Perklorat' }, { s: 'NO₂⁻', n: 'Nitrit' }, { s: 'SO₃²⁻', n: 'Sülfit' },
        { s: 'S₂O₃²⁻', n: 'Tiyosülfat' }, { s: 'CrO₄²⁻', n: 'Kromat' }, { s: 'Cr₂O₇²⁻', n: 'Dikromat' }, { s: 'C₂O₄²⁻', n: 'Oksalat' },
        { s: 'MnO₄²⁻', n: 'Manganat' }, { s: 'BO₃³⁻', n: 'Borat' }, { s: 'Fe(CN)₆⁴⁻', n: 'Ferrosiyanür' }, { s: 'Fe(CN)₆³⁻', n: 'Ferrisiyanür' },
        { s: 'Sb', n: 'Antimon' }, { s: 'Bi', n: 'Bizmut' }, { s: 'Po', n: 'Polonyum' }, { s: 'At', n: 'Astatin' },
        { s: 'Rn', n: 'Radon' }, { s: 'Fr', n: 'Fransiyum' }, { s: 'Ra', n: 'Radyum' }, { s: 'Ac', n: 'Aktinyum' },
        { s: 'Th', n: 'Toryum' }, { s: 'Pa', n: 'Protaktinyum' }, { s: 'U', n: 'Uranyum' }, { s: 'Np', n: 'Neptunyum' },
        { s: 'Pu', n: 'Plutonyum' }, { s: 'Am', n: 'Amerikyum' }, { s: 'Cm', n: 'Küriyum' }, { s: 'Bk', n: 'Berkelyum' },
        { s: 'Cf', n: 'Kaliforniyum' }, { s: 'Es', n: 'Aynştaynyum' }, { s: 'Fm', n: 'Fermiyum' }, { s: 'Md', n: 'Mendelevyum' },
        { s: 'No', n: 'Nobelyum' }, { s: 'Lr', n: 'Lavrensiyum' }, { s: 'Rf', n: 'Rutherfordiyum' }, { s: 'Db', n: 'Dubniyum' },
        { s: 'Sg', n: 'Seaborgiyum' }, { s: 'Bh', n: 'Bohriyum' }, { s: 'Hs', n: 'Hassiyum' }, { s: 'Mt', n: 'Meitneriyum' },
        { s: 'Ds', n: 'Darmstadtiyum' }, { s: 'Rg', n: 'Röntgenyum' }, { s: 'Cn', n: 'Kopernikyum' }, { s: 'Nh', n: 'Nihonyum' },
        { s: 'Fl', n: 'Flerovyum' }, { s: 'Mc', n: 'Moskovyum' }, { s: 'Lv', n: 'Livermoryum' }, { s: 'Ts', n: 'Tennessin' },
        { s: 'Og', n: 'Oganesson' }, { s: 'Rb', n: 'Rubidyum' }, { s: 'Sr', n: 'Stronsiyum' }, { s: 'Y', n: 'İtriyum' },
        { s: 'Zr', n: 'Zirkonyum' }, { s: 'Nb', n: 'Niyobyum' }, { s: 'Mo', n: 'Molibden' }, { s: 'Tc', n: 'Teknesyum' },
        { s: 'Ru', n: 'Rutenyum' }, { s: 'Rh', n: 'Rodyum' }, { s: 'Pd', n: 'Paladyum' }, { s: 'Cd', n: 'Kadmiyum' },
        { s: 'In', n: 'İndiyum' }, { s: 'Te', n: 'Tellür' }, { s: 'Xe', n: 'Ksenon' }, { s: 'Cs', n: 'Sezyum' },
        { s: 'Ba', n: 'Baryum' }, { s: 'La', n: 'Lantan' }, { s: 'Ce', n: 'Seryum' }, { s: 'Pr', n: 'Prasedim' },
        { s: 'Nd', n: 'Neodimyum' }, { s: 'Sm', n: 'Samaryum' }, { s: 'Eu', n: 'Europiyum' }, { s: 'Gd', n: 'Gadolinyum' }
    ]
};

const utils = {
    getRandomItem: (arr) => arr[Math.floor(Math.random() * arr.length)],
    shuffleArray: (arr) => {
        const a = [...arr];
        for (let i = a.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [a[i], a[j]] = [a[j], a[i]];
        }
        return a;
    },
    getWrongAnswers: (correct, count, type) => {
        const pool = KIMYALAB_DATA[type] || KIMYALAB_DATA.elements;
        // Cevap türünü (Sembol mü İsim mi) girdi üzerinden tespit et
        const isSymbol = pool.some(e => (e.s || e.symbol) === correct);
        
        // SADECE aynı kategoriden veya benzer uzunlukta şıklar seçerek "Sızmayı" (Farklılığı) engelle
        const filtered = pool.filter(e => {
            const sym = e.s || e.symbol;
            const name = e.name || (typeof e.n === 'string' ? e.n : null);
            return sym !== correct && name !== correct;
        });

        return utils.shuffleArray(filtered).slice(0, count).map(e => {
            if (isSymbol) return (e.s || e.symbol);
            return e.name || (typeof e.n === 'string' ? e.n : e.name);
        });
    }
};
