import re
import io

with io.open('data.js', 'r', encoding='utf-8') as f:
    text = f.read()

# Replace lab_guvenlik
lab = r'''        {
            id: 'lab_guvenlik',
            name: 'LABORATUVAR GÜVENLİK SEMBOLLERİ',
            desc: 'Kimyasalların üzerindeki tehlike işaretleri ve anlamları.',
            content: `Laboratuvarda güvenli çalışma için piktogramları tanımak hayati önem taşır:
            • <b>Yanıcı (Alev):</b> Kolay tutuşan maddeler. Alkol, aseton gibi.
            • <b>Yakıcı (Oksitleyici):</b> Başka maddelerin yanmasını sağlayan, O harfi üzerinde alev sembolü. Hidrojen peroksit gibi.
            • <b>Korozif (Aşındırıcı):</b> Ciltte veya metalde aşınma yapan maddeler. Kuvvetli asit ve bazlar.
            • <b>Toksik (Zehirli):</b> Vücuda girdiğinde ciddi zararlar veren (kurukafa sembolü).
            • <b>Çevreye Zararlı:</b> Doğaya atıldığında zararlı olan, balık ve ağaç sembolü.`,
            questions: [
                { q: "O harfi üzerinde alev sembolü neyi ifade eder?", options: ["Yanıcı", "Yakıcı", "Zehirli", "Radyoaktif"], a: "Yakıcı", difficulty: 'easy', hint: "Alevin altında O (oksijen) harfi bulunur.", explanation: "Oksitleyici (yakıcı) maddelerin sembolünde O harfi üzerinde alev bulunur. Oksijen yanmayı destekler." },
                { q: "Asit kaplarının üzerinde hangi sembolün bulunması beklenir?", options: ["Korozif", "Yanıcı", "Radyoaktif", "Patlayıcı"], a: "Korozif", difficulty: 'easy', hint: "Asitler metalleri aşındırır.", explanation: "Kuvvetli asitler ve bazlar korozif (aşındırıcı) etkiye sahiptir." },
                { q: "Kurukafa sembolü ne anlama gelir?", options: ["Toksik (Zehirli)", "Yakıcı", "Tahriş Edici", "Ekolojik Risk"], a: "Toksik (Zehirli)", difficulty: 'easy', hint: "Ölümcül tehlikeyi işaret eder.", explanation: "Kurukafa ve kemik sembolü, maddenin zehirli olduğunu gösterir." },
                { q: "Ünlem işareti (!) sembolü neyi belirtir?", options: ["Tahriş Edici", "Toksik", "Radyoaktif", "Yanıcı"], a: "Tahriş Edici", difficulty: 'medium', hint: "Göz ve cilt için rahatsız edici olabilir.", explanation: "Ünlem işareti, solunum yolu veya cilt tahrişine yol açabilen kimyasalları gösterir." },
                { q: "Ölü balık ve kurumuş ağaç sembolü neyi ifade eder?", options: ["Çevreye Zararlı", "Biyolojik Tehlike", "Su kirliliği", "Atık madde"], a: "Çevreye Zararlı", difficulty: 'medium', hint: "Doğal yaşamı tehdit eder.", explanation: "Bu maddeler doğaya karıştığında ekosisteme ağır zararlar verir." },
                { q: "HF (Hidroflorik asit) gibi maddeler neden özel kaplarda saklanmalıdır?", options: ["Camı aşındırdığı için", "Yanıcı olduğu için", "Pahalı olduğu için", "Kokusu olduğu için"], a: "Camı aşındırdığı için", difficulty: 'hard', hint: "Plastik kaplarda saklanırlar.", explanation: "HF zayıf bir asit olmasına rağmen camı delebilen (aşındıran) nadir asitlerdendir." },
                { q: "Laboratuvarda bir kimyasalın güvenlik bilgi formuna ne ad verilir?", options: ["MSDS", "HPLC", "ASTM", "TSE"], a: "MSDS", difficulty: 'hard', hint: "Malzeme Güvenlik Bilgi Formu'nun İngilizce kısaltmasıdır.", explanation: "MSDS (Material Safety Data Sheet), maddelerin riskleri hakkında detaylı bilgi içerir." },
                { q: "Radyoaktif maddelerle çalışılırken hangi kurşun önlük giyilmesinin temel sebebi nedir?", options: ["Radyasyonu emmek", "Sıcaklıktan korumak", "Ağırlık yapmak", "Şık durmak"], a: "Radyasyonu emmek", difficulty: 'medium', hint: "Kurşun yüksek yoğunlukludur.", explanation: "Kurşun tabakası zararlı radyoaktif ışınların (gama ve X-ışını) vücuda ulaşmasını engeller." },
                { q: "LPG ve doğalgaz tankları üzerinde hangi sembol mutlaka bulunur?", options: ["Yanıcı", "Oksitleyici", "Korozif", "Toksik"], a: "Yanıcı", difficulty: 'easy', hint: "Küçük bir kıvılcımda parlayabilirler.", explanation: "LPG gibi gazlar havayla karıştıktan sonra küçük bir kıvılcımla yanar ve patlayabilir." },
                { q: "Bir kimyasalın kanserojen olduğunu belirten sembolde ne tasvir edilir?", options: ["Göğüste yıldız şekli", "Kurukafa", "Ünlem", "Alev"], a: "Göğüste yıldız şekli", difficulty: 'medium', hint: "İnsan sağlığını içten bozan bir simgedir.", explanation: "İnsan silüeti üzerinde yıldız gibi çatlak şekli, sağlığa ciddi tehlike (kanserojen, mutajen) demektir." },
                { q: "Patlayıcı maddeler için kullanılan sembol hangisidir?", options: ["Dağılan parçalar", "Alev", "Ölü ağaç", "Çarpı işareti"], a: "Dağılan parçalar", difficulty: 'easy', hint: "Bir bombanın patlaması anını andırır.", explanation: "Patlayan bomba (dağılan parçalar) sembolü patlayıcı (explosive) kimyasalları işaret eder." },
                { q: "Basınçlı kaplar üzerindeki sembol hangisidir?", options: ["Gaz tüpü", "Alev", "Ünlem", "Pervane"], a: "Gaz tüpü", difficulty: 'easy', hint: "Silindir şeklindedir.", explanation: "Sıkıştırılmış, sıvılaştırılmış veya çözünmüş gazları temsil eder." },
                { q: "Biyolojik tehlike sembolü (Biohazard) nerede görülür?", options: ["Tıbbi atıklarda", "Asit şişelerinde", "Tuz paketlerinde", "Ocaklarda"], a: "Tıbbi atıklarda", difficulty: 'medium', hint: "Hastane atıkları buna örnektir.", explanation: "Enfeksiyon veya virüs riski taşıyan biyolojik tıbbi atıklarda (kan, enjektör) bu amblem kullanılır." },
                { q: "Gözlük ve eldiven kullanımını zorunlu kılan kural hangisidir?", options: ["Kişisel Koruyucu Donanım", "Laboratuvar Hijyeni", "Analiz Metodu", "Genel Temizlik"], a: "Kişisel Koruyucu Donanım", difficulty: 'easy', hint: "Güvenlik için giyilen eşyalardır (KKD).", explanation: "Laboratuvarda güvenliği sağlayan önlük, eldiven ve gözlük KKD kapsamında yer alır." },
                { q: "Cam balon ve erlenmayer arasındaki temel fark nedir?", options: ["Taban şekli", "Hacmi", "Rengi", "Malzemesi"], a: "Taban şekli", difficulty: 'medium', hint: "Biri düz diğeri yuvarlaktır.", explanation: "Cam balonun tabanı tamamen yuvarlaktır, erlenmayer ise geniş düz bir tabana sahip konik gövdelidir." },
                { q: "Titrasyon işlemlerinde kullanılan musluklu cam alet hangisidir?", options: ["Büret", "Pipet", "Mezur", "Beher"], a: "Büret", difficulty: 'medium', hint: "Dik durur ve damla damla sıvı akıtır.", explanation: "Musluklu dereceli cam boruya büret denir, hacim ölçümü ve titrasyon için şarttır." },
                { q: "Hassas sıvı aktarımlarında kullanılan alet hangisidir?", options: ["Pipet", "Huni", "Ayırma Hunisi", "Cam Çubuk"], a: "Pipet", difficulty: 'easy', hint: "Sıvıyı içine çekip dar yerlere boşaltır.", explanation: "Küçük miktardaki sıvıları çok hassas ölçerek başka bir kaba aktaran cam tüplere pipet denir." },
                { q: "Zeytinyağı ve suyu (iki karışmayan sıvı) ayırmak için ne kullanılır?", options: ["Ayırma hunisi", "Süzgeç kağıdı", "Cam balon", "Havan"], a: "Ayırma hunisi", difficulty: 'hard', hint: "Yoğunluk farkıyla çalışan musluklu bir hunidir.", explanation: "Birbirine karışmayan heterojen sıvı karışımları özkütle farkıyla ayrıştıran musluklu cam damıtma aletidir." },
                { q: "Katı maddeleri toz haline getirmek için ne kullanılır?", options: ["Havan", "Desikatör", "Kroze", "Saat camı"], a: "Havan", difficulty: 'medium', hint: "Porselen veya camdan yapılan ezici alet.", explanation: "Kimyasalları ezerek tanecik boyutunu küçültmeye yarayan laboratuvar porselenine havan denir." },
                { q: "Maddelerin nemini almak veya nemsiz ortamda saklamak için kullanılır?", options: ["Desikatör", "Etüv", "Bek alevi", "İspirto ocağı"], a: "Desikatör", difficulty: 'hard', hint: "Dibinde nem çekici madde olan kapaklı cam kasedir.", explanation: "İçinde silikajel gibi nem alıcı maddeler bulundurup maddeleri kuru muhafaza etmeye yarayan kalın cam kaptır." }
            ]
        }'''

# Replace modern_atom
atom = r'''        {
            id: 'modern_atom',
            name: 'MODERN ATOM TEORİSİ',
            desc: 'Kuantum modeli, orbitaller ve periyodik sistem.',
            content: `Modern atom teorisi (Kuantum Modeli), elektronun yerinin tam olarak belirlenemeyeceğini, sadece bulunma olasılığının yüksek olduğu bölgeler (orbitaller) olduğunu savunur.
            • <b>Baş kuantum sayısı (n):</b> Enerji düzeyini belirtir.
            • <b>Açısal momentum kuantum sayısı (l):</b> Orbitalin şeklini belirtir (s:0, p:1, d:2, f:3).
            • <b>Elektron Dizilimi İstisnaları:</b> 24Cr ([Ar] 4s1 3d5) ve 29Cu ([Ar] 4s1 3d10) küresel simetri nedeni ile istisnadır.`,
            questions: [
                { q: "Elektronların bulunma olasılığının yüksek olduğu bölgelere ne denir?", options: ["Yörünge", "Orbital", "Çekirdek", "Katman"], a: "Orbital", difficulty: 'easy', hint: "Yörünge klasik modele aittir.", explanation: "Kuantum modeline göre elektronlar kesin yörüngelerde değil, bulunma ihtimali yüksek olan orbitallerdedir." },
                { q: "l=1 kuantum sayısı hangi orbital türünü temsil eder?", options: ["s", "p", "d", "f"], a: "p", difficulty: 'easy', hint: "0=s, 1=_, 2=d", explanation: "Açısal momentum kuantum sayısı l=1 olan orbital p orbitalidir ve dumbell şeklindedir." },
                { q: "24Cr atomunun elektron dizilimi aşağıdakilerden hangisidir?", options: ["[Ar] 4s2 3d4", "[Ar] 4s1 3d5", "[Ar] 4s0 3d6", "[Ne] 3s2 3p6"], a: "[Ar] 4s1 3d5", difficulty: 'hard', hint: "Küresel simetriye ulaşmak için enerji düşürür.", explanation: "Krom, s2 d4 yerine küresel simetrinin kararlılığını sağlamak için s1 d5 elektron dizilimine sahip bir istisnadır." },
                { q: "Pauli dışlama ilkesine göre bir orbitalde en fazla kaç elektron bulunabilir?", options: ["1", "2", "6", "10"], a: "2", difficulty: 'easy', hint: "Elektronların zıt spinleri olmalıdır.", explanation: "Pauli prensibine göre hiçbir elektronun 4 kuantum sayısı aynı olamayacağı için bir orbitale zıt spinli en fazla 2 elektron girer." },
                { q: "d orbitali en fazla kaç elektron alabilir?", options: ["2", "6", "10", "14"], a: "10", difficulty: 'medium', hint: "5 tane d orbitali vardır.", explanation: "Alt kabuk olan d'de 5 adet alt orbital bulunur. Her biri 2 elektron aldığı için toplam 10 elektron kapasitesi vardır." },
                { q: "H2SO4 bileşiğinde Kükürt (S) atomunun yükseltgenme basamağı nedir?", options: ["+2", "+4", "+6", "-2"], a: "+6", difficulty: 'medium', hint: "H(+1) ve O(-2) değerliklerini kullanın.", explanation: "Toplam yük sıfırdır: 2*(+1) + S + 4*(-2) = 0 formülünden Kükürt +6 çıkar." },
                { q: "29Cu atomunun elektron diziliminde l=0 olan kaç elektron vardır?", options: ["6", "7", "8", "9"], a: "7", difficulty: 'hard', hint: "l=0, yani 's' orbitallerindeki toplam elektrondur.", explanation: "Cu istisnadır ([Ar] 4s1 3d10). 1s2, 2s2, 3s2, 4s1 orbitallerindeki elektron toplamı 2+2+2+1 = 7 elektron yapar." },
                { q: "4d orbitali için baş kuantum sayısı (n) ve orbital şekli (l) nedir?", options: ["n=4, l=2", "n=4, l=1", "n=3, l=2", "n=5, l=0"], a: "n=4, l=2", difficulty: 'medium', hint: "d orbitalinin l değeri 2'dir.", explanation: "Orbitalin katsayısı n=4'ü, 'd' harfi ise l=2'yi temsil eder." },
                { q: "Bir orbitalde n=3 ve l=1 ise bu orbital hangisidir?", options: ["3s", "3p", "3d", "2p"], a: "3p", difficulty: 'easy', hint: "l=1 olduğuna göre bu p orbitalidir.", explanation: "n=3 baş kuantum seviyesi 3. enerji düzeyi demektir, l=1 p orbitaline işaret eder, dolayısıyla 3p'dir." },
                { q: "KMnO4 bileşiğinde Mn elementinin yükseltgenme basamağı?", options: ["+5", "+6", "+7", "+2"], a: "+7", difficulty: 'hard', hint: "K(+1) ve O(-2) değerliklerini topla.", explanation: "K(+1) ve Mn + 4*O(-2) = 0 formülünden Mn - 7 = 0 olur, dolayısıyla +7 değerini alır." },
                { q: "Heisenberg Belirsizlik İlkesi neyi savunur?", options: ["Konum ve hız aynı anda bilinemez", "Orbitalleri", "Proton sayısını", "Atom kütlesini"], a: "Konum ve hız aynı anda bilinemez", difficulty: 'medium', hint: "Elektron o kadar hızlı ve küçüktür ki tespit çok zordur.", explanation: "Elektron gibi çok hızlı ve küçük taneciklerin konumu ve momentumu (veya hızı) aynı anda hata payı sıfır ölçülemez." },
                { q: "Manyetik kuantum sayısı (ml) l=2 için hangi değerleri alabilir?", options: ["0, 1", "-1, 0, 1", "-2'den +2'ye kadar", "Sadece 0"], a: "-2'den +2'ye kadar", difficulty: 'medium', hint: "ml, -l ile +l arasındadır.", explanation: "l=2 d orbitalidir ve -2, -1, 0, +1, +2 olmak üzere toplam 5 orbitali temsil eden ml değerlerini alabilir." },
                { q: "Spin kuantum sayısı (ms) hangi değerleri alabilir?", options: ["0, 1", "+1/2, -1/2", "1, 2, 3", "-l, +l"], a: "+1/2, -1/2", difficulty: 'easy', hint: "Spin dönme yönüyle ilgilidir.", explanation: "Elektronlar saat yönü ve tersi olmak üzere +1/2 ve -1/2 kuantum numaralarıyla ifade edilir." },
                { q: "Hund Kuralı aşağıdakilerden hangisi ile ilgilidir?", options: ["Orbitallere önce teker teker yerleşme", "Baş kuantum sayısı", "Işık hızı", "Atom çapı"], a: "Orbitallere önce teker teker yerleşme", difficulty: 'medium', hint: "Elektronlar aynı enerjili yerlere önce paralel yerleşir.", explanation: "Eş enerjili orbitallere elektronların önce aynı spinle birer birer (yarı dolu), sonra zıt spinle tam doldurularak girmesi kuralıdır." },
                { q: "4s orbitalinin enerjisi 3d orbitalinden neden daha düşüktür?", options: ["n+l değeri daha düşük olduğu için", "Daha büyük olduğu için", "Daha çok elektron aldığı için", "Çekirdeğe uzak olduğu için"], a: "n+l değeri daha düşük olduğu için", difficulty: 'hard', hint: "Madelung-Klechkowski Kuralı ile ilgilidir.", explanation: "4s için n+l = 4+0=4 iken, 3d için n+l = 3+2=5'tir. n+l değeri düşük olanın enerjisi de düşüktür." },
                { q: "Periyodik sistemde aynı grupta yukarıdan aşağıya inildikçe çap nasıl değişir?", options: ["Artar", "Azalır", "Değişmez", "Önce artar sonra azalır"], a: "Artar", difficulty: 'easy', hint: "Aşağıya katman sayısı eklenir.", explanation: "Baş kuantum sayısı (katman sayısı) arttığı için dış yörünge çekirdekten uzaklaşır ve atom hacmi artar." },
                { q: "Elektronegatifliği en yüksek olan element hangisidir?", options: ["F (Flor)", "O (Oksijen)", "Fr (Fransiyum)", "Cs (Sezyum)"], a: "F (Flor)", difficulty: 'easy', hint: "Tabloda en sağ üstteki halojendir.", explanation: "Bağ elektronlarını çekme gücü elektronegatifliktir; Flor, Pauling ölçeğine göre en yüksek elektronegatif olan elementtir (4.0)." },
                { q: "Gaz halindeki bir atomdan elektron koparmak için gereken minimum enerjiye ne denir?", options: ["İyonlaşma enerjisi", "Elektron ilgisi", "Elektronegatiflik", "Bağ enerjisi"], a: "İyonlaşma enerjisi", difficulty: 'medium', hint: "Atomun katyonlaşması olayıdır.", explanation: "Sıfır yüklü gaz atomdan çok uzak diyara (- sonsuz) bir elektronu zorla almak için verilen ilk kuvvete 1. İyonlaşma Enerjisi denir." },
                { q: "Periyodik tabloda 3. periyot 5A grubunda bulunan atomun proton sayısı?", options: ["13", "15", "17", "11"], a: "15", difficulty: 'hard', hint: "Katmanlar 2, 8, ... şeklinde dağılır.", explanation: "3 katmanı ve son katmanında 5 elektronu var: 2, 8, 5 dizilimini toplarsak proton sayısı (nötr iken elektronuna) 15 olur (Fosfor)." },
                { q: "Geçiş metalleri (B grupları) hangi orbitallerle biter?", options: ["s veya p", "d", "f", "Sadece s"], a: "d", difficulty: 'medium', hint: "Kuantum seviyesinde ortadaki o büyük boşluktur.", explanation: "Geçiş elementleri elektron diziliminde daima d orbitali ile bitmektedir." }
            ]
        }'''

# Replace gazlar
gaz = r'''        {
            id: 'gazlar',
            name: 'GAZLAR',
            desc: 'Gaz yasaları, ideal gas denklemi ve kinetik teori.',
            content: `Gazların davranışlarını açıklayan temel yasalar ve kavramlar:
            • <b>İdeal Gaz Denklemi:</b> P.V = n.R.T
            • <b>Kinetik Teori:</b> Gazların hızı sıcaklığın kareköküyle doğru, mol kütlesinin kareköküyle ters orantılıdır (V1/V2 = √(M2/M1) * √(T1/T2)).`,
            questions: [
                { q: "Avogadro Yasasına göre aynı koşullarda eşit hacimli gazların nesi eşittir?", options: ["Kütleleri", "Molekül sayıları", "Yoğunlukları", "Hızları"], a: "Molekül sayıları", difficulty: 'medium', hint: "Mol sayıları eşittir.", explanation: "Sıcaklık ve basınç aynıysa, eşit hacimlerdeki ideal tüm gazların mol sayısı (dolayısıyla molekül sayısı) eşittir." },
                { q: "Gazların yayılma hızı (difüzyon) sıcaklıkla nasıl değişir?", options: ["Kareköküyle doğru orantılı", "Doğru orantılı", "Ters orantılı", "Etkilemez"], a: "Kareköküyle doğru orantılı", difficulty: 'hard', hint: "Formülde Kinetik Enerji T'ye, Hız v'ye bağlıdır.", explanation: "Kinetik teoriye göre ortalama molekül hızı, sıcaklığın (Kelvin) kareköküyle doğru artar." },
                { q: "Mutlak sıfır noktası kaç Kelvin'dir?", options: ["0 K", "273 K", "-273 K", "100 K"], a: "0 K", difficulty: 'easy', hint: "Hareketin tamamen durduğu varsayılan noktadır.", explanation: "-273,15 °C olan noktaya Kelvin ölçeğinde 0 K denmektedir ve teorik en düşük sıcaklıktır." },
                { q: "Gay-Lussac Yasası hangi değişkenleri sabit hacimde inceler?", options: ["Basınç-Sıcaklık", "Hacim-Miktar", "Basınç-Hacim", "Miktar-Sıcaklık"], a: "Basınç-Sıcaklık", difficulty: 'medium', hint: "Isınan kapalı gazın patlamasıyla ilgilidir.", explanation: "Hacim (V) sabitken sıcaklık artarsa basıncın da artacağını açıklar." },
                { q: "Basınç birimi olan 1 atm kaç cmHg değerine eşittir?", options: ["76", "100", "760", "1.013"], a: "76", difficulty: 'easy', hint: "Toricelli'nin barometre deneyinden gelir.", explanation: "Deniz seviyesinde 0 °C'de cıvalı barometre 76 cm kadar yüksekliğe ulaşır (760 mm Hg)." },
                { q: "Gerçek gazların sıvılaşabildiği en yüksek sıcaklığa ne denir?", options: ["Kritik sıcaklık", "Yüzleşme sıcaklığı", "Kaynama noktası", "Donma noktası"], a: "Kritik sıcaklık", difficulty: 'hard', hint: "Bu sıcaklığın üstünde gaz hiçbir basınçla sıvılaşamaz.", explanation: "Kritik sıcaklığın (Tk) altındaki fazlarına buhar, üstündekilere soğutulsalar dahi sıvılaşmayan gerçek gaz denir." },
                { q: "Joule-Thomson olayı nedir?", options: ["Gazların genişlerken soğuması", "Gazların yanması", "Gazların karışması", "Gazların iyonlaşması"], a: "Gazların genişlerken soğuması", difficulty: 'hard', hint: "Buzdolabı teknolojisinin altyapısıdır.", explanation: "Küçük bir delikten aniden genleşen gaz moleküllerinin aralarındaki bağı koparmak için kendi enerjilerini kullanarak soğumasına denir." },
                { q: "Sabit hacimli bir kapta sıcaklık 2 katına (Kelvin) çıkarsa basınç nasıl değişir?", options: ["2 katına çıkar", "Yarıya iner", "4 katına çıkar", "Değişmez"], a: "2 katına çıkar", difficulty: 'medium', hint: "P ve T doğru orantılıdır (P.V = n.R.T).", explanation: "Hesaplamalar daima Kelvin ile yapılır. T(K) iki katına çıkarsa eşitlik gereği Basınç(P) da iki katına çıkar." },
                { q: "H2 gazının (MA:2) hızı O2 gazının (MA:32) hızının kaç katıdır?", options: ["4", "16", "2", "8"], a: "4", difficulty: 'hard', hint: "Graham yasasında mol kütlelerinin bölümünün karekökü alınır.", explanation: "√(32/2) = √16 = 4. Yani hafif olan H2 gazı O2'den 4 kat daha hızlı yayılır." },
                { q: "Kısmi basınç hesabı yapılırken hangisinden yararlanılır?", options: ["Mol kesri", "Mol kütlesi", "Hacim", "Sıcaklık"], a: "Mol kesri", difficulty: 'medium', hint: "Gaz karışımındaki payından bahsediyoruz.", explanation: "Bir gazın kısmi basıncı o gazın Mol Kesri (X) ile Toplam Basıncın (Pt) çarpımına (Pb=Xb*Pt) eşittir." },
                { q: "Hava bir gaz karışımıdır. Havadaki en bol gaz hangisidir?", options: ["Azot (N2)", "Oksijen (O2)", "Argon", "CO2"], a: "Azot (N2)", difficulty: 'easy', hint: "Hacimce %78 oranındadır.", explanation: "Kuru havanın yaklaşık %78'i Azot (N2) ve %21'i Oksijen (O2) gazından ibarettir." },
                { q: "Hangi gaz hava yastıklarında ani şişmeyi sağlar?", options: ["Azot gazı (N2)", "Oksijen (O2)", "Helyum", "Hidrojen"], a: "Azot gazı (N2)", difficulty: 'medium', hint: "Çarpma anında sodyum azid tuzu bozunarak oluşur.", explanation: "Hava yastıklarında bulunan Sodyum azid (NaN3) elektriksel kıvılcımla hızlıca bozunup zehirsiz yüksek hacimli N2 gazı üretir." },
                { q: "Graham Difüzyon Yasası neyi açıklar?", options: ["Gazların yayılma hızını", "Patlama katsayısını", "Gaz çözünürlüğünü", "Erime reaksiyonunu"], a: "Gazların yayılma hızını", difficulty: 'medium', hint: "Moleküllerin birbiri içerisinde difüzyonu ile ilgilidir.", explanation: "Hafif gazların ağır gazlara nazaran difüzyon/efüzyon hızının yüksek olmasını matematiksel modeller." },
                { q: "İdeal gazlarda moleküller arası çekim kuvvetleri nasıldır?", options: ["Yok sayılır", "Çok güçlüdür", "Su gibidir", "Sıcaklıkla artar"], a: "Yok sayılır", difficulty: 'easy', hint: "O yüzden teorik / ideal ismini alır.", explanation: "İdeal gaz varsayımında çarpışmalar esnek ve moleküller arası etkileşim sıfır(yok) kabul edilir." },
                { q: "Birim yüzeye yapılan gaz çarpma sayısı neye bağlıdır?", options: ["Basınç ve derişim", "Sadece Hacim", "Maddenin Rengi", "Yer çekimi"], a: "Basınç ve derişim", difficulty: 'hard', hint: "Parçacık yoğunluğuna ve parçacık hızına bağlıdır.", explanation: "Bir yüzeye yapılan çarpma sayısı; birim hacimdeki molekül sayısına (derişime) ve aynı zamanda molekülün yayılma hızına (sıcaklık, MA) doğrudan ilişkilidir." },
                { q: "Boyle-Mariotte yasası hangi iki değişken arasındaki ilişkiyi inceler?", options: ["Basınç-Hacim", "Basınç-Sıcaklık", "Madde Miktarı-Hacim", "Mol-Basınç"], a: "Basınç-Hacim", difficulty: 'easy', hint: "Şırınganın ucunu kapatıp bastırmak buna örnektir.", explanation: "Sabit sıcaklıktaki belirli miktar bir gazın hacmiyle (V) basıncının (P) ters orantılı olduğunu anlatır." },
                { q: "Charles yasasına göre, sabit basınçta bir gazın hacmi neyle doğru orantılıdır?", options: ["Mutlak sıcaklık (K)", "Mol kütlesi", "Basınç", "Zaman"], a: "Mutlak sıcaklık (K)", difficulty: 'medium', hint: "Sıcak uçan balonun havaya yükselmesinin temelidir.", explanation: "Sıcaklık arttıkça ideal gazın genleşerek hacminin genişleyeceğini ispatlar." },
                { q: "STP (Standart Sıcaklık ve Basınç) değerleri nelerdir?", options: ["0 °C ve 1 atm", "25 °C ve 1 atm", "100 °C ve 2 atm", "25 °C ve 0 atm"], a: "0 °C ve 1 atm", difficulty: 'easy', hint: "Donma noktasına yakındır.", explanation: "Uluslararası standartlarda STP denilen durum, sıfır Santigrat derece sıcaklığı ve 1 atmosfer basıncı belirtir." },
                { q: "Normal koşullarda (NK) 1 mol ideal ideal kaç litre hacim kaplar?", options: ["22,4 L", "11,2 L", "24,5 L", "44,8 L"], a: "22,4 L", difficulty: 'easy', hint: "Yirmi iki virgül dörttür.", explanation: "Standart 0 °C ve 1 atm (NK) koşullarında bir gazın formülü ne olursa olsun 1 molü daima 22,4 L hacimlidir." },
                { q: "Kısmi basınçların toplamı sistemin toplam basıncına eşittir diyen yasa kime aittir?", options: ["Dalton", "Boyle", "Charles", "Gay-Lussac"], a: "Dalton", difficulty: 'medium', hint: "Aynı zamanda ilk bilimsel atom teorisinin de sahibi.", explanation: "Dalton Kısmi Basınçlar Yasası, bir gaz karışımının yaptığı toplam basıncın, içindeki her bir gazın basınçlarının mutlak toplamıyla bulunduğunu belirtir." }
            ]
        }'''

import re
text = re.sub(r'\{\s*id:\s*\'lab_guvenlik\'.*?\}\s*,\s*\{\s*id:\s*\'modern_atom\'.*?\}', lab + ',\n' + atom, text, flags=re.DOTALL)
text = re.sub(r'\{\s*id:\s*\'gazlar\'.*?\}\s*,\s*\{\s*id:\s*\'cozeltiler\'', gaz + ',\n        {\n            id: \'cozeltiler\'', text, flags=re.DOTALL)

with io.open('data.js', 'w', encoding='utf-8') as f:
    f.write(text)

print("done")
